//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1_MVVM.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab1_MVVM.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка к элементам (без VM).
        /// </summary>
        internal static string Direct_Group {
            get {
                return ResourceManager.GetString("Direct_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите текст:.
        /// </summary>
        internal static string Enter_Text {
            get {
                return ResourceManager.GetString("Enter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка через ViewModel.
        /// </summary>
        internal static string Group_ViaVM {
            get {
                return ResourceManager.GetString("Group_ViaVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛР2 - Локализация (RESX).
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать сообщение.
        /// </summary>
        internal static string Message_Button {
            get {
                return ResourceManager.GetString("Message_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, мир!.
        /// </summary>
        internal static string MessageBox_Text {
            get {
                return ResourceManager.GetString("MessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        internal static string Name_Label {
            get {
                return ResourceManager.GetString("Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус (обновляется через кнопку):.
        /// </summary>
        internal static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        internal static string Tab1_Header {
            get {
                return ResourceManager.GetString("Tab1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        internal static string Tab2_Header {
            get {
                return ResourceManager.GetString("Tab2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string Tab3_Header {
            get {
                return ResourceManager.GetString("Tab3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонние привязки.
        /// </summary>
        internal static string Tab4_Header {
            get {
                return ResourceManager.GetString("Tab4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Tab5_Header {
            get {
                return ResourceManager.GetString("Tab5_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить статус.
        /// </summary>
        internal static string Update_Button {
            get {
                return ResourceManager.GetString("Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели:.
        /// </summary>
        internal static string YouEntered {
            get {
                return ResourceManager.GetString("YouEntered", resourceCulture);
            }
        }
    }
}
